name: audio_meta
description: audio information extraction (duration, bitrate, sample rate, channels) from audio files
version: 2.0.0
repo: https://github.com/Milchkonsument/audio_meta
repository: https://github.com/Milchkonsument/audio_meta

environment:
  sdk: ^3.0.0

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
